### ISSUE TITLE
Pids should not be hoisted because it causes to return pids for previous processes

### ISSUE THREAD

**Issue by michalkvasnicak** [radiovisual/port-pid#1]
https://github.com/radiovisual/port-pid/blob/master/index.js#L8 this should not be hoisted because it can return pids for previous port number.

Example:

You have process `A` listening on port 3000
You have process `B` listening on port 3001

If you call `port-pid(3000)` everything is ok, but when you call `port-pid(3001)` it returns pids for process `A` and `B`.

**Comment by radiovisual** [comment]
Oh! nice catch. Thanks for pointing this out. I don't have time to fix this until later today or tomorrow, so if you would like to send in a PR, I am happy to merge. 👍

**Comment by radiovisual** [comment]
This is getting fixed in #6

**Comment by radiovisual** [comment]
This has been fixed in the `0.0.7` release. Sorry for the late response to all this. If you still see problems, please open a new issue. Thanks for reporting!
