### ISSUE TITLE
process.platform seems to clash with the process() function

### ISSUE THREAD

**Issue by TheSLX** [radiovisual/port-pid#2]
I couldn't get the library to work until I noticed platform was undefined.
With some fiddling I noticed that it worked fine when I renamed your "process()" function to something different.
Could be system related but I thought I'd let you know.

**Comment by radiovisual** [comment]
What platform/OS are you using?

**Comment by TheSLX** [comment]
Sorry for the late response, the notifications got buried.

I'm using Windows 10 and the 6.1.3 version of node.
(npm 3.10.10, but I'm mainly using Yarn)

**Comment by radiovisual** [comment]
This ~will get~ has been fixed in the `0.0.7` release. Sorry for the late response to all this. If you still see problems, please open a new issue. Thanks for reporting!
